# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Danny Denenberg
tagline:          A Jew from Nebraska ğŸˆ
description:      A Jew from Nebraska ğŸˆ
url:              http://denenberg.us
baseurl:          /

author:
  name:           Danny Denenberg
  url:            https://twitter.com/denenbergdanny

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
